### ISSUE TITLE
add data availability option for ggpedigree

### ISSUE THREAD

**Issue by JulienGAMartin** [JulienGAMartin/pedtricks#11]
should we add the option in drawPedigree to plot with color only individuals for which we have phenotypic data (dat argument in drawPedigree) ?

**Comment by susjoh** [comment]
Yes, should be possible with an additional argument - do you mean the points?

**Comment by susjoh** [comment]
I have added a pheno argument that plots links to unknown parents with a grey line (colour can be specified).
