### ISSUE TITLE
warning messages "replacing previous import" 

### ISSUE THREAD

**Issue by susjoh** [JulienGAMartin/pedtricks#9]
My latest [commit](https://github.com/JulienGAMartin/pedtricks/commit/4bf8a9bb8606210a58963245937727bcb73ffd55) is now resulting in the following warning, which I'm not sure how to solve:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/8b9a273b-070d-4faa-b586-8c6549981f1c">

Flagging it as an issue here in case you both have a solution...

**Comment by susjoh** [comment]
Fixed by importing specific commands from igraph. @JulienGAMartin is it normal just to import the specific functions rather than whole packages? Please let me know if you'd like me to do that...

**Comment by JulienGAMartin** [comment]
Hi Susan
On holidays with limited internet

This is the recommended usage on import
Import only the function you need from each package to avoid conflict.

Given the use of ggplot I think ggplot2 and dplyr should be fully imported but for others we can import only the needed functions

Cheers

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by matthewwolak** [comment]
I concur with @JulienGAMartin for only importing specific functions. That means lines in [R/pedtricks-package.R](https://github.com/JulienGAMartin/pedtricks/blob/42524fafe5a32950f87e6aa869345aea2524dd12/R/pedtricks-package.R) that would look like, for example:
```
#' @importFrom igraph layout_with_sugiyama graph_from_data_frame
```
with potentially more functions following.

However, we have to be careful in case the `igraph` functions you do call require other `igraph` functions that cause conflicts like the ones in the warning message.

Am I assuming/seeing correctly that you have not explicitly used the `igraph` functions that have the same name as `dplyr` or `tidyr` functions noted in the warning messages? If so we should be OK with the above solution with `@importFrom`.

**Comment by susjoh** [comment]
Thanks for the advice :) after a bit of testing it seems to be okay to just import the two functions. I was also not specifying it in [R/pedtricks-package.R](https://github.com/JulienGAMartin/pedtricks/blob/42524fafe5a32950f87e6aa869345aea2524dd12/R/pedtricks-package.R), naughty.
